$(document).ready(function(){

  $('#about').on('click',function(){
    $("#aboutSection").show();
    $("#projectSection").hide();
    $("#blogSection").hide();
    $('#contactSection').hide();
  })
  $('#projects').on('click',function(){
    $("#aboutSection").hide();
    $("#projectSection").show();
    $("#blogSection").hide();
    $('#contactSection').hide();
  })
  $('#blog').on('click',function(){
    $("#aboutSection").hide();
    $("#projectSection").hide();
    $("#blogSection").show();
    $('#contactSection').hide();
  })
  $('#contact').on('click',function(){
    $("#aboutSection").hide();
    $("#projectSection").hide();
    $("#blogSection").hide();
    $('#contactSection').show();
  })
});
